<h1>Blog HTML</h1>

<table>
    <tr>
        <td>ID</td>
        <td>TITLE</td>
        <td>DESCRIPTION</td>
    </tr>
    <?php foreach( $posts as $item ): ?>
    <tr>
        <td><?php echo $this->escapeHtml( $item['id'] ); ?></td>
        <td><?php echo $this->escapeHtml( $item['title'] ); ?></td>
        <td><?php echo $this->escapeHtml( $item['description'] ); ?></td>
    </tr>
    <?php endforeach; ?>

</table>
